### ISSUE TITLE
Problem with generating story2.html

### ISSUE THREAD

**Issue by joerugg** [ajam/tarbell-big-read-template#5]
Followed the instructions here [https://github.com/ajam/tarbell-big-read-template#creating-multiple-pages](url) to create an additional page in the tarbell big-read template, However, when I generate the projects I get a slew of errors in Mac OS Terminal. It looks like everything is generated correctly with the exception of story2.html, which is missing from the generated site files.

Here's the output from the terminal after generating files:

`joes-mac-mini:SecondTest Joe$ tarbell generate stage012

Traceback (most recent call last):

  File "/usr/local/bin/tarbell", line 11, in <module>

    sys.exit(main())

  File "/usr/local/lib/python2.7/site-packages/tarbell/cli.py", line 74, in main

    command.__call__(command, args)

  File "/usr/local/lib/python2.7/site-packages/tarbell/cli.py", line 931, in __call__

    return self.fn(*args, **kw_args)

  File "/usr/local/lib/python2.7/site-packages/tarbell/cli.py", line 170, in tarbell_generate

    site.generate_static_site(output_root, extra_context)

  File "/usr/local/lib/python2.7/site-packages/tarbell/app.py", line 714, in generate_static_site

    self.freezer.freeze()

  File "/usr/local/lib/python2.7/site-packages/flask_frozen/__init__.py", line 149, in freeze

    new_filename = self._build_one(url)

  File "/usr/local/lib/python2.7/site-packages/flask_frozen/__init__.py", line 257, in _build_one

    base_url=base_url)

  File "/usr/local/lib/python2.7/site-packages/werkzeug/test.py", line 778, in get

    return self.open(*args, **kw)

  File "/usr/local/lib/python2.7/site-packages/flask/testing.py", line 108, in open

    follow_redirects=follow_redirects)

  File "/usr/local/lib/python2.7/site-packages/werkzeug/test.py", line 751, in open

    response = self.run_wsgi_app(environ, buffered=buffered)

  File "/usr/local/lib/python2.7/site-packages/werkzeug/test.py", line 668, in run_wsgi_app

    rv = run_wsgi_app(self.application, environ, buffered=buffered)

  File "/usr/local/lib/python2.7/site-packages/werkzeug/test.py", line 871, in run_wsgi_app

    app_rv = app(environ, start_response)

  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__

    return self.wsgi_app(environ, start_response)

  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app

    response = self.make_response(self.handle_exception(e))

  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception

    reraise(exc_type, exc_value, tb)

  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app

    response = self.full_dispatch_request()

  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request

    rv = self.handle_user_exception(e)

  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception

    reraise(exc_type, exc_value, tb)

  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request

    rv = self.dispatch_request()

  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

  File "/usr/local/lib/python2.7/site-packages/tarbell/app.py", line 538, in preview

    rendered = render_template(path, **context)

  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template

    context, ctx.app)

  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 110, in _render

    rv = template.render(context)

  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render

    return self.environment.handle_exception(exc_info, True)

  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception

    reraise(exc_type, exc_value, tb)

  File "/Users/Joe/TarbellTheDay/SecondTest/story2.html", line 1, in top-level template code

    {% extends '_base.html' %}

  File "/Users/Joe/TarbellTheDay/SecondTest/_base.html", line 70, in top-level template code

    {% block content %}

  File "/Users/Joe/TarbellTheDay/SecondTest/story2.html", line 31, in block "content"

    {% include '_content.html' %}

  File "/Users/Joe/TarbellTheDay/SecondTest/_content.html", line 3, in top-level template code

    {% block content %}

  File "/Users/Joe/TarbellTheDay/SecondTest/_content.html", line 18, in block "content"

    {{ macros.build_content(content, right_rail, images) }}

  File "/Users/Joe/TarbellTheDay/SecondTest/_macros.html", line 6, in template

    {{ build_text(row, right_rail, images) }}

  File "/Users/Joe/TarbellTheDay/SecondTest/_macros.html", line 24, in template

    <p>{{ text_row.value.replace("\n", "</p><p>") | replaceMarkdownLinks | safe }}</p>

  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 397, in getattr

    return getattr(obj, attribute)

jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'value'`

**Not sure what's happened here. Any ideas?**

**Comment by joannaskao** [comment]
Hmm. Is it running locally properly (e.g. when you visit http://localhost:5000/story2.html)? If it's also not working there, I'm guessing that there's an error in one of the new sheets you created to support story2 — check that the tabs in the Google Spreadsheet are named correctly and that all the column headers are still correct. Let me know how those go?

**Comment by joerugg** [comment]
Thanks, joannaskao! It was indeed a problem with the google sheet. One of the tabs had an empty space before the sheet name. Removed that and re-generated and all is well.

**Comment by joannaskao** [comment]
Awesome! Glad to hear it.
