### ISSUE TITLE
Install Trouble

### ISSUE THREAD

**Issue by cgobbet** [ajam/tarbell-big-read-template#6]
Hello;

I am a longtime fan but never could use Tarbell because my previous employer had security policies too strict for me to do it. Now I moved to another job and I am installing it for good to start working with it.

I am trying to follow the Big Read template, but cannot install nor virtualenvwrapper nor Tarbell itself. Trying to find out the error, I found out that the error message  trying to install virtualenvwrapper or Tarbell were relatively similar.

Here's virtualenvwrapper:

`Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/var/folders/27/z8r2xh990m5_h0vyz584sb340000gp/T/pip-6FZtjW-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'`

here's Tarbell

`Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/werkzeug'`

I then went to check where the installs were. Python was on usr/bin, while virtualenv was on local/bin.

Still just for the records, both Pip and Homebrew are installed and apparently normal.

My questions:

1) should I uninstall and install everything again? If so, which are the commands?

2) if I can go to install it, which are the commands so the installation process go until the end?

Two years ago, I managed to install Tarbell on my computer but this time it's not working, even if I went though the same path as before. If anyone can give some light here it would be greatly appreciated

Thanks in advance

**Comment by joannaskao** [comment]
We've solved this offline. We needed to install virtualenvwrapper using `sudo pip install virtualenvwrapper --ignore-installed six` and then follow the setup instructions in `/usr/local/bin/virtualenvwrapper.sh`

<img width="425" alt="screen shot 2017-09-29 at 9 18 02 am" src="https://user-images.githubusercontent.com/1794257/31018301-8ba5cb26-a4f9-11e7-8719-aead7ab582bc.png">
