### ISSUE TITLE
Can't install Tarbell

### ISSUE THREAD

**Issue by jovempan2** [ajam/tarbell-big-read-template#7]
Hello;

I am installing Tarbell and after installing Python, Virtualenv and Virtualenvwrapper successfully, Tarbell is not going on. This is the error message I get:

************************************************************************************

Mac:~ [myusername]$ sudo pip install tarbell
Password:
The directory '/Users/[myusername]/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/[myusername]/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting tarbell
  Downloading tarbell-1.0.7.tar.gz
Collecting Flask==0.10.1 (from tarbell)
  Downloading Flask-0.10.1.tar.gz (544kB)
    100% |████████████████████████████████| 552kB 1.2MB/s 
Collecting Frozen-Flask==0.11 (from tarbell)
  Downloading Frozen-Flask-0.11.tar.gz (106kB)
    100% |████████████████████████████████| 112kB 4.2MB/s 
Collecting Jinja2==2.7.3 (from tarbell)
  Downloading Jinja2-2.7.3.tar.gz (378kB)
    100% |████████████████████████████████| 378kB 2.1MB/s 
Collecting Markdown==2.4.1 (from tarbell)
  Downloading Markdown-2.4.1.tar.gz (279kB)
    100% |████████████████████████████████| 286kB 2.1MB/s 
Collecting MarkupSafe==0.23 (from tarbell)
  Downloading MarkupSafe-0.23.tar.gz
Collecting PyYAML==3.11 (from tarbell)
  Downloading PyYAML-3.11.zip (371kB)
    100% |████████████████████████████████| 378kB 1.7MB/s 
Collecting boto==2.38.0 (from tarbell)
  Downloading boto-2.38.0-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 437kB/s 
Collecting clint==0.4.1 (from tarbell)
  Downloading clint-0.4.1.tar.gz
Collecting gnureadline==6.3.3 (from tarbell)
  Downloading gnureadline-6.3.3-cp27-none-macosx_10_9_x86_64.whl (132kB)
    100% |████████████████████████████████| 133kB 2.2MB/s 
Collecting google-api-python-client==1.3.1 (from tarbell)
  Downloading google-api-python-client-1.3.1.tar.gz (40kB)
    100% |████████████████████████████████| 40kB 5.8MB/s 
Collecting keyring==5.3 (from tarbell)
  Downloading keyring-5.3.zip (87kB)
    100% |████████████████████████████████| 92kB 5.5MB/s 
Collecting oauth2client==1.5.2 (from tarbell)
  Downloading oauth2client-1.5.2.tar.gz (56kB)
    100% |████████████████████████████████| 61kB 4.8MB/s 
Collecting python-dateutil>=2.2 (from tarbell)
  Downloading python_dateutil-2.6.1-py2.py3-none-any.whl (194kB)
    100% |████████████████████████████████| 194kB 3.1MB/s 
Collecting requests==2.3.0 (from tarbell)
  Downloading requests-2.3.0-py2.py3-none-any.whl (452kB)
    100% |████████████████████████████████| 460kB 1.4MB/s 
Collecting sh==1.09 (from tarbell)
  Downloading sh-1.09.tar.gz
Requirement already satisfied: wsgiref==0.1.2 in /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7 (from tarbell)
Collecting xlrd==0.9.3 (from tarbell)
  Downloading xlrd-0.9.3.tar.gz (178kB)
    100% |████████████████████████████████| 184kB 2.9MB/s 
Collecting Werkzeug>=0.7 (from Flask==0.10.1->tarbell)
  Downloading Werkzeug-0.12.2-py2.py3-none-any.whl (312kB)
    100% |████████████████████████████████| 317kB 972kB/s 
Collecting itsdangerous>=0.21 (from Flask==0.10.1->tarbell)
  Downloading itsdangerous-0.24.tar.gz (46kB)
    100% |████████████████████████████████| 51kB 2.8MB/s 
Collecting args (from clint==0.4.1->tarbell)
  Downloading args-0.1.0.tar.gz
Collecting httplib2>=0.8 (from google-api-python-client==1.3.1->tarbell)
  Downloading httplib2-0.10.3.tar.gz (204kB)
    100% |████████████████████████████████| 204kB 2.4MB/s 
Collecting uritemplate>=0.6 (from google-api-python-client==1.3.1->tarbell)
  Downloading uritemplate-3.0.0-py2.py3-none-any.whl
Collecting pyasn1>=0.1.7 (from oauth2client==1.5.2->tarbell)
  Downloading pyasn1-0.3.6-py2.py3-none-any.whl (63kB)
    100% |████████████████████████████████| 71kB 4.2MB/s 
Collecting pyasn1-modules>=0.0.5 (from oauth2client==1.5.2->tarbell)
  Downloading pyasn1_modules-0.1.4-py2.py3-none-any.whl (60kB)
    100% |████████████████████████████████| 61kB 4.0MB/s 
Collecting rsa>=3.1.4 (from oauth2client==1.5.2->tarbell)
  Downloading rsa-3.4.2-py2.py3-none-any.whl (46kB)
    100% |████████████████████████████████| 51kB 4.5MB/s 
Collecting six>=1.6.1 (from oauth2client==1.5.2->tarbell)
  Downloading six-1.11.0-py2.py3-none-any.whl
Installing collected packages: Werkzeug, MarkupSafe, Jinja2, itsdangerous, Flask, Frozen-Flask, Markdown, PyYAML, boto, args, clint, gnureadline, httplib2, pyasn1, pyasn1-modules, rsa, six, oauth2client, uritemplate, google-api-python-client, keyring, python-dateutil, requests, sh, xlrd, tarbell
  Running setup.py install for MarkupSafe ... done
  Running setup.py install for Jinja2 ... done
  Running setup.py install for itsdangerous ... done
  Running setup.py install for Flask ... done
  Running setup.py install for Frozen-Flask ... done
  Running setup.py install for Markdown ... done
  Running setup.py install for PyYAML ... done
  Running setup.py install for args ... done
  Running setup.py install for clint ... done
  Running setup.py install for httplib2 ... done
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/tmp/pip-_W3u1m-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'
Mac:~ [myusername]$ 

************************************************************************************
What can I do to proceed?

Thanks in advance

**Comment by joannaskao** [comment]
What happens if you try `sudo pip install tarbell --ignore-installed six`?
